In [12]:
import pandas as pd

index = 'A B C D E'
columnadi = 'W X Y Z'

columnadi = columnadi.split()
index = index.split()  
import numpy as np
data = np.random.randn(5,4)


df = pd.DataFrame(data,index = index,columns = columnadi)

df

          W         X         Y         Z
A -0.890330 -1.815864 -1.921867 -0.869228
B  0.017785 -1.164783  0.493298 -0.247490
C -1.041781 -0.682437  1.474426 -0.017783
D  1.066670  1.172751 -1.789662  0.775463
E  0.253896  1.175492 -0.460099 -1.172601

In [14]:
df[["W","Z"]]

          W         Z
A -0.890330 -0.869228
B  0.017785 -0.247490
C -1.041781 -0.017783
D  1.066670  0.775463
E  0.253896 -1.172601

In [20]:
df["new"]=df["W"]+df["Z"]
df

          W         X         Y         Z       new
A -0.890330 -1.815864 -1.921867 -0.869228 -1.759559
B  0.017785 -1.164783  0.493298 -0.247490 -0.229705
C -1.041781 -0.682437  1.474426 -0.017783 -1.059565
D  1.066670  1.172751 -1.789662  0.775463  1.842133
E  0.253896  1.175492 -0.460099 -1.172601 -0.918706

In [23]:
data2=np.random.randint(18, 66, 5)
df["age"]=data2
df

          W         X         Y         Z       new  age
A -0.890330 -1.815864 -1.921867 -0.869228 -1.759559   52
B  0.017785 -1.164783  0.493298 -0.247490 -0.229705   22
C -1.041781 -0.682437  1.474426 -0.017783 -1.059565   18
D  1.066670  1.172751 -1.789662  0.775463  1.842133   57
E  0.253896  1.175492 -0.460099 -1.172601 -0.918706   35