In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = pd.read_excel("marketing_data.xlsx")
df

,ï»¿ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Country
0,1826,1970,Graduation,Divorced,"$84,835.00",0.0,0,6/16/2014,SP
1,1,1961,Graduation,Single,"$57,091.00",0.0,0,6/15/2014,CA
2,10699,1985,Graduation,Married,"$44,322.00",1.0,0,6/16/2014,SA
3,7516,1983,Graduation,Married,"$30,096.00",1.0,0,5/22/2014,GER
4,3129,1983,Graduation,Married,"$30,096.00",1.0,0,5/22/2014,SP
...,...,...,...,...,...,...,...,...,...
610,10142,1976,PhD,Divorced,"$66,476.00",0.0,1,3/7/2013,US
611,5263,1977,2n Cycle,Married,"$31,056.00",1.0,0,1/22/2013,SP
612,22,1976,Graduation,Divorced,"$46,310.00",1.0,0,12/3/2012,SP
613,528,1978,Graduation,Married,"$65,819.00",0.0,0,11/29/2012,IND
614,4070,1969,PhD,Married,"$94,871.00",0.0,2,9/1/2012,CA

In [8]:
'''
1) Sizə verilən datanı pandas vasitəsilə oxudun
2) İlk və son 6 dəyərinə baxın
3) İlk sütunun adını dəyişərək “First_İD” edin
4) Datadakı sütun adlarını çıxarın(3-cü sualdakı dəyişikliyi yoxlayın)
5) Datada boş(Null) dəyərlərin olub-olmadığını, varsa hansı sütun(sütunlarda)
olduğunu göstərin
6) “Kidhome” sütununda boş dəyərlər varsa, həmin sütunun ortalaması ilə doldurun,
daha sonra yoxlayın
7) “İncome” sütununda $ işarəsin silin və int tipinə çevirin
8) Datada neçə sətir və sütun olduğunu çıxarın
9) “Education” sütununda olan dublikat olmayan dəyərləri çıxardın
10) “PhD” dərəcəsində olan neçə müştəri olduğunu göstərin
11) İlk və son qeydiyyatdan keçən müştərilərin qeydiyyatdan keçmə tarixlərini
göstərin
12) “Marital_Statusa” əsasən qruplaşdırma aparıb ortalama gəliri (“income”)
göstərin
'''
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ï»¿ID           615 non-null    int64
 1   Year_Birth      615 non-null    int64
 2   Education       615 non-null    object
 3   Marital_Status  615 non-null    object
 4    Income         580 non-null    object
 5   Kidhome         571 non-null    float64
 6   Teenhome        615 non-null    int64
 7   Dt_Customer     615 non-null    object
 8   Country         615 non-null    object
dtypes: float64(1), int64(3), object(5)
memory usage: 43.4+ KB

In [11]:
df.describe()

              ï»¿ID   Year_Birth     Kidhome    Teenhome
count    615.000000   615.000000  571.000000  615.000000
mean    5495.310569  1968.613008    0.450088    0.500813
std     3240.459784    11.721795    0.541809    0.555912
min        1.000000  1900.000000    0.000000    0.000000
25%     2743.500000  1959.000000    0.000000    0.000000
50%     5346.000000  1969.000000    0.000000    0.000000
75%     8147.000000  1977.000000    1.000000    1.000000
max    11188.000000  1996.000000    2.000000    2.000000

In [13]:
 df.isnull().sum()

ï»¿ID              0
Year_Birth         0
Education          0
Marital_Status     0
 Income           35
Kidhome           44
Teenhome           0
Dt_Customer        0
Country            0
dtype: int64

In [17]:
#2) İlk və son 6 dəyərinə baxın
df.head(6)

,ï»¿ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Country
0,1826,1970,Graduation,Divorced,"$84,835.00",0.0,0,6/16/2014,SP
1,1,1961,Graduation,Single,"$57,091.00",0.0,0,6/15/2014,CA
2,10699,1985,Graduation,Married,"$44,322.00",1.0,0,6/16/2014,SA
3,7516,1983,Graduation,Married,"$30,096.00",1.0,0,5/22/2014,GER
4,3129,1983,Graduation,Married,"$30,096.00",1.0,0,5/22/2014,SP
5,5121,1977,Graduation,Single,"$56,628.00",0.0,1,3/21/2014,CA

In [19]:
df.tail(6)

,ï»¿ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Country
609,9977,1973,Graduation,Divorced,"$78,901.00",0.0,1,9/17/2013,US
610,10142,1976,PhD,Divorced,"$66,476.00",0.0,1,3/7/2013,US
611,5263,1977,2n Cycle,Married,"$31,056.00",1.0,0,1/22/2013,SP
612,22,1976,Graduation,Divorced,"$46,310.00",1.0,0,12/3/2012,SP
613,528,1978,Graduation,Married,"$65,819.00",0.0,0,11/29/2012,IND
614,4070,1969,PhD,Married,"$94,871.00",0.0,2,9/1/2012,CA

In [23]:
#3) İlk sütunun adını dəyişərək “First_İD” edin
#df.rename(columns={'old_col1': 'new_col1', 

df=df.rename(columns={'ï»¿ID':'First_ID'})

df

,First_ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Country
0,1826,1970,Graduation,Divorced,"$84,835.00",0.0,0,6/16/2014,SP
1,1,1961,Graduation,Single,"$57,091.00",0.0,0,6/15/2014,CA
2,10699,1985,Graduation,Married,"$44,322.00",1.0,0,6/16/2014,SA
3,7516,1983,Graduation,Married,"$30,096.00",1.0,0,5/22/2014,GER
4,3129,1983,Graduation,Married,"$30,096.00",1.0,0,5/22/2014,SP
...,...,...,...,...,...,...,...,...,...
610,10142,1976,PhD,Divorced,"$66,476.00",0.0,1,3/7/2013,US
611,5263,1977,2n Cycle,Married,"$31,056.00",1.0,0,1/22/2013,SP
612,22,1976,Graduation,Divorced,"$46,310.00",1.0,0,12/3/2012,SP
613,528,1978,Graduation,Married,"$65,819.00",0.0,0,11/29/2012,IND
614,4070,1969,PhD,Married,"$94,871.00",0.0,2,9/1/2012,CA

In [29]:
#4) Datadakı sütun adlarını çıxarın(3-cü sualdakı dəyişikliyi yoxlayın)
df.columns

Index(['First_ID', 'Year_Birth', 'Education', 'Marital_Status', ' Income ',
       'Kidhome', 'Teenhome', 'Dt_Customer', 'Country'],
      dtype='object')

In [32]:
#5) Datada boş(Null) dəyərlərin olub-olmadığını, varsa hansı sütun(sütunlarda)
#olduğunu göstərin
df.isnull().sum()

First_ID           0
Year_Birth         0
Education          0
Marital_Status     0
 Income           35
Kidhome           44
Teenhome           0
Dt_Customer        0
Country            0
dtype: int64

In [34]:
#6) “Kidhome” sütununda boş dəyərlər varsa, həmin sütunun ortalaması ilə doldurun,
#daha sonra yoxlayın

df[df["Kidhome"].isna()]

,First_ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Country
51,9703,1970,PhD,Married,"$38,097.00",NaN,1,10/15/2012,SA
52,6927,1968,PhD,Married,"$44,377.00",NaN,1,10/5/2012,SA
62,1665,1964,PhD,Divorced,"$64,140.00",NaN,2,9/23/2013,SA
63,10640,1974,Graduation,Together,"$44,392.00",NaN,1,9/5/2013,SP
64,7620,1990,Basic,Single,"$16,185.00",NaN,0,8/5/2013,IND
65,7761,1978,2n Cycle,Together,"$38,702.00",NaN,0,8/1/2013,AUS
71,8780,1950,PhD,Together,"$59,292.00",NaN,1,6/13/2013,SP
72,2276,1955,Graduation,Single,"$57,959.00",NaN,1,5/2/2013,SP
73,1172,1983,PhD,Married,"$92,491.00",NaN,0,5/1/2013,SP
429,10323,1952,Graduation,Married,"$49,413.00",NaN,1,10/25/2013,SP
430,4682,1958,Graduation,Married,"$51,876.00",NaN,0,10/15/2013,GER
431,3083,1974,Graduation,Married,"$45,837.00",NaN,1,7/26/2013,SP
432,8015,1962,PhD,Divorced,"$85,696.00",NaN,0,5/3/2013,SP
433,1745,1962,PhD,Divorced,"$85,696.00",NaN,0,5/3/2013,SP
441,692,1954,Graduation,Together,"$36,807.00",NaN,1,12/20/2012,IND
442,7706,1975,2n Cycle,Together,"$46,772.00",NaN,1,11/7/2012,CA
455,1404,1968,Graduation,Together,"$34,916.00",NaN,0,5/15/2013,SA
456,10598,1967,Graduation,Together,"$27,943.00",NaN,1,4/15/2013,SP
457,8212,1971,Master,Married,"$39,791.00",NaN,1,3/28/2013,SP
458,3233,1965,PhD,Married,"$62,745.00",NaN,1,3/23/2013,SA
459,7892,1969,Graduation,Single,"$18,589.00",NaN,0,1/2/2013,US
460,2975,1976,Graduation,Together,"$85,606.00",NaN,1,11/12/2012,SP
461,5043,1951,Basic,Married,"$26,997.00",NaN,0,11/5/2012,SP
462,3104,1961,Graduation,Single,"$82,332.00",NaN,0,9/17/2012,GER
463,10854,1970,PhD,Married,"$38,853.00",NaN,1,5/23/2014,IND
483,1833,1974,PhD,Single,"$39,190.00",NaN,0,4/26/2014,SP
484,7270,1981,Graduation,Divorced,"$56,981.00",NaN,0,1/25/2014,SA
485,8182,1984,Graduation,Married,"$23,228.00",NaN,0,1/5/2014,CA
486,10394,1984,Graduation,Married,"$90,000.00",NaN,0,12/23/2013,CA
505,6515,1977,Graduation,Together,NaN,NaN,0,12/6/2013,SA
506,5954,1972,Master,Divorced,"$42,618.00",NaN,0,10/9/2013,SP
507,7938,1958,PhD,Together,"$51,518.00",NaN,1,10/3/2013,GER
508,961,1972,Graduation,Married,"$74,716.00",NaN,1,9/12/2013,SP
513,4179,1959,Graduation,Together,NaN,NaN,0,8/20/2013,SP
514,2292,1985,Graduation,Single,NaN,NaN,0,8/2/2013,SP
515,9239,1961,Master,Married,NaN,NaN,2,7/26/2013,US
516,8953,1965,Master,Single,"$35,791.00",NaN,1,5/6/2013,SP
539,2661,1964,Graduation,Single,NaN,NaN,1,6/4/2013,SA
540,3130,1964,Graduation,Single,"$18,701.00",NaN,1,6/4/2013,SP
541,5847,1969,Graduation,Divorced,"$69,901.00",NaN,1,5/29/2013,SP
542,5863,1953,Graduation,Married,"$47,703.00",NaN,1,5/29/2013,SP
546,5589,1964,Graduation,Divorced,NaN,NaN,1,8/31/2012,IND
547,10172,1988,Graduation,Single,NaN,NaN,0,8/10/2012,SP
548,6729,1988,Graduation,Single,"$68,655.00",NaN,0,8/10/2012,SA

In [38]:
df["Kidhome"].fillna(df["Kidhome"].mean(), inplace= True)

df[df["Kidhome"].isna()]

/var/folders/qy/0qtnbdzn1pb0vd98b2s698n40000gn/T/ipykernel_3319/1756095003.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Kidhome"].fillna(df["Kidhome"].mean(), inplace= True)

Empty DataFrame
Columns: [First_ID, Year_Birth, Education, Marital_Status,  Income , Kidhome, Teenhome, Dt_Customer, Country]
Index: []

In [56]:
#7) “İncome” sütununda $ işarəsin silin və int tipinə çevirin
#df.replace(2, 200, inplace=True)
#df[" Income "].replace("$", "", inplace=True)
df[" Income "].str.replace("$", "", regex=False)

0      84,835.00
1      57,091.00
2      44,322.00
3      30,096.00
4      30,096.00
          ...
610    66,476.00
611    31,056.00
612    46,310.00
613    65,819.00
614    94,871.00
Name:  Income , Length: 615, dtype: object

In [126]:
df

,First_ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Country
0,1826,1970,Graduation,Divorced,84835,0.0,0,2014-06-16,SP
1,1,1961,Graduation,Single,57091,0.0,0,2014-06-15,CA
2,10699,1985,Graduation,Married,44322,1.0,0,2014-06-16,SA
3,7516,1983,Graduation,Married,30096,1.0,0,2014-05-22,GER
4,3129,1983,Graduation,Married,30096,1.0,0,2014-05-22,SP
...,...,...,...,...,...,...,...,...,...
610,10142,1976,PhD,Divorced,66476,0.0,1,2013-03-07,US
611,5263,1977,2n Cycle,Married,31056,1.0,0,2013-01-22,SP
612,22,1976,Graduation,Divorced,46310,1.0,0,2012-12-03,SP
613,528,1978,Graduation,Married,65819,0.0,0,2012-11-29,IND
614,4070,1969,PhD,Married,94871,0.0,2,2012-09-01,CA

In [ ]:
df[" Income "] = (
    df[" Income "]
    .astype(str)
    .str.strip()
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace(".00", "", regex=False)
    .astype(int)
) ## errorlu

In [67]:
df

,First_ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Country
0,1826,1970,Graduation,Divorced,"$84,835.00",0.0,0,6/16/2014,SP
1,1,1961,Graduation,Single,"$57,091.00",0.0,0,6/15/2014,CA
2,10699,1985,Graduation,Married,"$44,322.00",1.0,0,6/16/2014,SA
3,7516,1983,Graduation,Married,"$30,096.00",1.0,0,5/22/2014,GER
4,3129,1983,Graduation,Married,"$30,096.00",1.0,0,5/22/2014,SP
...,...,...,...,...,...,...,...,...,...
610,10142,1976,PhD,Divorced,"$66,476.00",0.0,1,3/7/2013,US
611,5263,1977,2n Cycle,Married,"$31,056.00",1.0,0,1/22/2013,SP
612,22,1976,Graduation,Divorced,"$46,310.00",1.0,0,12/3/2012,SP
613,528,1978,Graduation,Married,"$65,819.00",0.0,0,11/29/2012,IND
614,4070,1969,PhD,Married,"$94,871.00",0.0,2,9/1/2012,CA

In [73]:
df[" Income "] = (df[" Income "].astype(str)                       # nan-lar string oldu  
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace(".00", "", regex=False)
)
df[" Income "] = pd.to_numeric(df[" Income "], errors="coerce").astype("Int64") ##inte cevirdi

df

,First_ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Country
0,1826,1970,Graduation,Divorced,84835,0.0,0,6/16/2014,SP
1,1,1961,Graduation,Single,57091,0.0,0,6/15/2014,CA
2,10699,1985,Graduation,Married,44322,1.0,0,6/16/2014,SA
3,7516,1983,Graduation,Married,30096,1.0,0,5/22/2014,GER
4,3129,1983,Graduation,Married,30096,1.0,0,5/22/2014,SP
...,...,...,...,...,...,...,...,...,...
610,10142,1976,PhD,Divorced,66476,0.0,1,3/7/2013,US
611,5263,1977,2n Cycle,Married,31056,1.0,0,1/22/2013,SP
612,22,1976,Graduation,Divorced,46310,1.0,0,12/3/2012,SP
613,528,1978,Graduation,Married,65819,0.0,0,11/29/2012,IND
614,4070,1969,PhD,Married,94871,0.0,2,9/1/2012,CA

In [80]:
#8) Datada neçə sətir və sütun olduğunu çıxarın
df.shape
#df.shape[0]-setr
#df.shape[1]-sutun

(615, 9)

In [82]:
#9) “Education” sütununda olan dublikat olmayan dəyərləri çıxardın
df["Education"].unique()

array(['Graduation', '2n Cycle', 'PhD', 'Master', 'Basic'], dtype=object)

In [86]:
#10) “PhD” dərəcəsində olan neçə müştəri olduğunu göstərin
df[df["Education"]=="PhD"].shape[0]

131

In [92]:
#11) İlk və son qeydiyyatdan keçən müştərilərin qeydiyyatdan keçmə tarixlərini
#göstərin
son_qeydiyyat=df["Dt_Customer"].max()
ilk_qeydiyyat=df["Dt_Customer"].min()
ilk_qeydiyyat

'1/1/2013'

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   First_ID        615 non-null    int64
 1   Year_Birth      615 non-null    int64
 2   Education       615 non-null    object
 3   Marital_Status  615 non-null    object
 4    Income         580 non-null    Int64
 5   Kidhome         615 non-null    float64
 6   Teenhome        615 non-null    int64
 7   Dt_Customer     615 non-null    object
 8   Country         615 non-null    object
dtypes: Int64(1), float64(1), int64(3), object(4)
memory usage: 44.0+ KB

In [99]:
df["Dt_Customer"] = pd.to_datetime(df["Dt_Customer"])

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   First_ID        615 non-null    int64
 1   Year_Birth      615 non-null    int64
 2   Education       615 non-null    object
 3   Marital_Status  615 non-null    object
 4    Income         580 non-null    Int64
 5   Kidhome         615 non-null    float64
 6   Teenhome        615 non-null    int64
 7   Dt_Customer     615 non-null    datetime64[ns]
 8   Country         615 non-null    object
dtypes: Int64(1), datetime64[ns](1), float64(1), int64(3), object(3)
memory usage: 44.0+ KB

In [103]:
son_qeydiyyat=df["Dt_Customer"].max()
ilk_qeydiyyat=df["Dt_Customer"].min()
son_qeydiyyat

Timestamp('2014-06-28 00:00:00')

In [104]:
#12) “Marital_Statusa” əsasən qruplaşdırma aparıb ortalama gəliri (“income”)
#göstərin

In [125]:
df.groupby(by="Marital_Status").mean(numeric_only=True)[" Income "]

Marital_Status
Divorced    55579.461538
Married     50894.149533
Single      53074.637037
Together    51688.938776
Widow       55643.578947
Name:  Income , dtype: Float64