In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [121]:
df = pd.read_excel("Sleep_health_and_lifestyle_dataset.xlsx")
df.head(10)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,2026-01-06 00:00:00,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,6,Male,28,Software Engineer,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Insomnia
6,7,Male,29,Teacher,2026-03-06 00:00:00,6,40,7,Obese,140/90,82,3500,Insomnia
7,8,Male,29,Doctor,2026-08-07 00:00:00,7,75,6,Normal,120/80,70,8000,NaN
8,9,Male,29,Doctor,2026-08-07 00:00:00,7,75,6,Normal,120/80,70,8000,NaN
9,10,Male,29,Doctor,2026-08-07 00:00:00,7,75,6,Normal,120/80,70,8000,NaN

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    object
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    object
dtypes: int64(7), object(6)
memory usage: 38.1+ KB

In [14]:
df.describe()

,Person ID,Age,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,187.500000,42.184492,7.312834,59.171123,5.385027,70.165775,6816.844920
std,108.108742,8.673133,1.196956,20.830804,1.774526,4.135676,1617.915679
min,1.000000,27.000000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,94.250000,35.250000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,187.500000,43.000000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,280.750000,50.000000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,374.000000,59.000000,9.000000,90.000000,8.000000,86.000000,10000.000000

In [15]:
'''
1) Person ID silin
2) Columnlara baxin, butun herflerini boyuk herfle yazin
3) Datanin nece sutun ve setirden ibaret olduguna baxin
4) Data haqqinda melumatlara baxin
   her sutunda nece null deyer var
   datada olan butun null deyerlerin sayina baxin
   typelari yoxlayin
   
5) Null deyer olan sutun adlarini cixarin
6) QUALITY OF SLEEP 6a beraber olan setirleri cixarin
7) SLEEP DISORDER i No_disease le doldurun
8) BLOOD PRESSURE sutununu 2 hisseye ayirin. /dan evvel ve /dan sonra. Her birini ayri sutunda yazin(elave 2 sutun yaradirsiniz. evvelkini sonra silin)
9) Typelari yoxlayin
10) Butun sutunlarda nadir deyerlerin sayina baxin
11) OCCUPATION sutununda nadir deyerlere baxin, her nadir deyerin sayina da baxin
12) Her sutun uzre ortalama cixarin
13) DAILY STEPS 10000den az olmayan ve SLEEP DURATION 8den az olmayan setirlere baxin
14) Yasi 56dan boyuk olanlarin Occupation a baxin
15) Datani yasa gore azalan sira ile duz
16) Indexleri yenile
17) Columns arasi elaqeye baxin
18) Her stress level uzre daily steps in ortalamasina baxin ve sonda daily steps sutununu artan sira ile duzun
19) Sleep disorder ve gender sutunlari arasinda cross seklinde melumatlari cixarin
20) Duplicatlarin sayina baxin
'''

'\n1) Person ID silin\n2) Columnlara baxin, butun herflerini boyuk herfle yazin\n3) Datanin nece sutun ve setirden ibaret olduguna baxin\n4) Data haqqinda melumatlara baxin\n   her sutunda nece null deyer var\n   datada olan butun null deyerlerin sayina baxin\n   typelari yoxlayin\n\n5) Null deyer olan sutun adlarini cixarin\n6) QUALITY OF SLEEP 6a beraber olan setirleri cixarin\n7) SLEEP DISORDER i No_disease le doldurun\n8) BLOOD PRESSURE sutununu 2 hisseye ayirin. /dan evvel ve /dan sonra. Her birini ayri sutunda yazin(elave 2 sutun yaradirsiniz. evvelkini sonra silin)\n9) Typelari yoxlayin\n10) Butun sutunlarda nadir deyerlerin sayina baxin\n11) OCCUPATION sutununda nadir deyerlere baxin, her nadir deyerin sayina da baxin\n12) Her sutun uzre ortalama cixarin\n13) DAILY STEPS 10000den az olmayan ve SLEEP DURATION 8den az olmayan setirlere baxin\n14) Yasi 56dan boyuk olanlarin Occupation a baxin\n15) Datani yasa gore azalan sira ile duz\n16) Indexleri yenile\n17) Columns arasi elaqeye baxin\n18) Her stress level uzre daily steps in ortalamasina baxin ve sonda daily steps sutununu artan sira ile duzun\n19) Sleep disorder ve gender sutunlari arasinda cross seklinde melumatlari cixarin\n20) Duplicatlarin sayina baxin\n'

In [135]:

#df.drop("Person ID", axis = 1, inplace=True)
df.head(5)

,GENDER,AGE,OCCUPATION,SLEEP DURATION,QUALITY OF SLEEP,PHYSICAL ACTIVITY LEVEL,STRESS LEVEL,BMI CATEGORY,BLOOD PRESSURE,HEART RATE,DAILY STEPS,SLEEP DISORDER
0,Male,27,Software Engineer,2026-01-06 00:00:00,6,42,6,Overweight,126/83,77,4200,No_disease
1,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,No_disease
2,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,No_disease
3,Male,28,Sales Representative,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,Male,28,Sales Representative,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [124]:
df.columns
#df.columns = df.columns.str.upper()
df.columns=df.columns.str.upper()
df.head(5)

,PERSON ID,GENDER,AGE,OCCUPATION,SLEEP DURATION,QUALITY OF SLEEP,PHYSICAL ACTIVITY LEVEL,STRESS LEVEL,BMI CATEGORY,BLOOD PRESSURE,HEART RATE,DAILY STEPS,SLEEP DISORDER
0,1,Male,27,Software Engineer,2026-01-06 00:00:00,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [25]:
#3) Datanin nece sutun ve setirden ibaret olduguna baxin
df.shape

(374, 12)

In [34]:
'''
4) Data haqqinda melumatlara baxin
   her sutunda nece null deyer var
   datada olan butun null deyerlerin sayina baxin
   typelari yoxlayin
'''

'\n4) Data haqqinda melumatlara baxin\n   her sutunda nece null deyer var\n   datada olan butun null deyerlerin sayina baxin\n   typelari yoxlayin\n'

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   GENDER                   374 non-null    object
 1   AGE                      374 non-null    int64
 2   OCCUPATION               374 non-null    object
 3   SLEEP DURATION           374 non-null    object
 4   QUALITY OF SLEEP         374 non-null    int64
 5   PHYSICAL ACTIVITY LEVEL  374 non-null    int64
 6   STRESS LEVEL             374 non-null    int64
 7   BMI CATEGORY             374 non-null    object
 8   BLOOD PRESSURE           374 non-null    object
 9   HEART RATE               374 non-null    int64
 10  DAILY STEPS              374 non-null    int64
 11  SLEEP DISORDER           155 non-null    object
dtypes: int64(6), object(6)
memory usage: 35.2+ KB

In [32]:
df.describe()

,AGE,QUALITY OF SLEEP,PHYSICAL ACTIVITY LEVEL,STRESS LEVEL,HEART RATE,DAILY STEPS
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,42.184492,7.312834,59.171123,5.385027,70.165775,6816.844920
std,8.673133,1.196956,20.830804,1.774526,4.135676,1617.915679
min,27.000000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,35.250000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,43.000000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,50.000000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,59.000000,9.000000,90.000000,8.000000,86.000000,10000.000000

In [38]:
 df.isnull().sum()

GENDER                       0
AGE                          0
OCCUPATION                   0
SLEEP DURATION               0
QUALITY OF SLEEP             0
PHYSICAL ACTIVITY LEVEL      0
STRESS LEVEL                 0
BMI CATEGORY                 0
BLOOD PRESSURE               0
HEART RATE                   0
DAILY STEPS                  0
SLEEP DISORDER             219
dtype: int64

In [43]:
#5) Null deyer olan sutun adlarini cixarin
df.columns[df.isnull().any()]

Index(['SLEEP DISORDER'], dtype='object')

In [58]:
#6) QUALITY OF SLEEP 6a beraber olan setirleri cixarin
df[df["QUALITY OF SLEEP"]==6]

,GENDER,AGE,OCCUPATION,SLEEP DURATION,QUALITY OF SLEEP,PHYSICAL ACTIVITY LEVEL,STRESS LEVEL,BMI CATEGORY,BLOOD PRESSURE,HEART RATE,DAILY STEPS,SLEEP DISORDER
0,Male,27,Software Engineer,2026-01-06 00:00:00,6,42,6,Overweight,126/83,77,4200,NaN
1,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,NaN
2,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,NaN
6,Male,29,Teacher,2026-03-06 00:00:00,6,40,7,Obese,140/90,82,3500,Insomnia
10,Male,29,Doctor,2026-01-06 00:00:00,6,30,8,Normal,120/80,70,8000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
296,Female,50,Nurse,2026-01-06 00:00:00,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
297,Female,50,Nurse,2026-01-06 00:00:00,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
303,Female,51,Nurse,6,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
304,Female,51,Nurse,2026-01-06 00:00:00,6,90,8,Overweight,140/95,75,10000,Sleep Apnea
305,Female,51,Nurse,2026-01-06 00:00:00,6,90,8,Overweight,140/95,75,10000,Sleep Apnea

In [127]:
#7) SLEEP DISORDER i No_disease le doldurun
df["SLEEP DISORDER"].fillna("No_disease", inplace= True)

df[df["SLEEP DISORDER"].isna()]

/var/folders/qy/0qtnbdzn1pb0vd98b2s698n40000gn/T/ipykernel_3452/4124488676.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["SLEEP DISORDER"].fillna("No_disease", inplace= True)

Empty DataFrame
Columns: [PERSON ID, GENDER, AGE, OCCUPATION, SLEEP DURATION, QUALITY OF SLEEP, PHYSICAL ACTIVITY LEVEL, STRESS LEVEL, BMI CATEGORY, BLOOD PRESSURE, HEART RATE, DAILY STEPS, SLEEP DISORDER]
Index: []

In [118]:
#8) BLOOD PRESSURE sutununu 2 hisseye ayirin. /dan evvel ve /dan sonra. Her birini ayri
#sutunda yazin(elave 2 sutun yaradirsiniz. evvelkini sonra silin)
#df[["BP_Systolic", "BP_Diastolic"]] = df["BLOOD PRESSURE"].str.split("/", expand=True)
df
#df = df.drop(columns=['BLOOD PRESSURE'])

,GENDER,AGE,OCCUPATION,SLEEP DURATION,QUALITY OF SLEEP,PHYSICAL ACTIVITY LEVEL,STRESS LEVEL,BMI CATEGORY,HEART RATE,DAILY STEPS,SLEEP DISORDER,BP_Systolic,BP_Diastolic
0,Male,27,Software Engineer,<NA>,6,42,6,Overweight,77,4200,No_disease,126,83
1,Male,28,Doctor,<NA>,6,60,8,Normal,75,10000,No_disease,125,80
2,Male,28,Doctor,<NA>,6,60,8,Normal,75,10000,No_disease,125,80
3,Male,28,Sales Representative,<NA>,4,30,8,Obese,85,3000,Sleep Apnea,140,90
4,Male,28,Sales Representative,<NA>,4,30,8,Obese,85,3000,Sleep Apnea,140,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,Female,59,Nurse,<NA>,9,75,3,Overweight,68,7000,Sleep Apnea,140,95
370,Female,59,Nurse,8,9,75,3,Overweight,68,7000,Sleep Apnea,140,95
371,Female,59,Nurse,<NA>,9,75,3,Overweight,68,7000,Sleep Apnea,140,95
372,Female,59,Nurse,<NA>,9,75,3,Overweight,68,7000,Sleep Apnea,140,95
373,Female,59,Nurse,<NA>,9,75,3,Overweight,68,7000,Sleep Apnea,140,95

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   GENDER                   374 non-null    object
 1   AGE                      374 non-null    int64
 2   OCCUPATION               374 non-null    object
 3   SLEEP DURATION           374 non-null    object
 4   QUALITY OF SLEEP         374 non-null    int64
 5   PHYSICAL ACTIVITY LEVEL  374 non-null    int64
 6   STRESS LEVEL             374 non-null    int64
 7   BMI CATEGORY             374 non-null    object
 8   HEART RATE               374 non-null    int64
 9   DAILY STEPS              374 non-null    int64
 10  SLEEP DISORDER           374 non-null    object
 11  BP_Systolic              374 non-null    object
 12  BP_Diastolic             374 non-null    object
dtypes: int64(6), object(7)
memory usage: 38.1+ KB

In [74]:
#10) Butun sutunlarda nadir deyerlerin sayina baxin
df["GENDER"].value_counts()

GENDER
Male      189
Female    185
Name: count, dtype: int64

In [76]:
df["AGE"].value_counts()

AGE
43    34
44    30
37    20
38    20
50    20
31    18
32    17
53    17
59    16
39    15
45    14
33    13
30    13
29    13
35    12
36    12
41    12
49    11
57     9
52     9
42     9
51     8
54     7
58     6
28     5
40     4
48     3
55     2
56     2
34     2
27     1
Name: count, dtype: int64

In [77]:
df["OCCUPATION"].value_counts()

OCCUPATION
Nurse                   73
Doctor                  71
Engineer                63
Lawyer                  47
Teacher                 40
Accountant              37
Salesperson             32
Software Engineer        4
Scientist                4
Sales Representative     2
Manager                  1
Name: count, dtype: int64

In [78]:
df["SLEEP DURATION"].value_counts()

SLEEP DURATION
2026-02-07 00:00:00    36
6                      31
2026-08-07 00:00:00    28
2026-05-06 00:00:00    26
2026-01-06 00:00:00    25
2026-07-07 00:00:00    24
2026-06-06 00:00:00    20
2026-01-07 00:00:00    19
2026-01-08 00:00:00    15
2026-03-07 00:00:00    14
2026-04-08 00:00:00    14
2026-03-06 00:00:00    13
2026-05-08 00:00:00    13
8                      13
2026-02-06 00:00:00    12
2026-02-08 00:00:00    11
2026-06-07 00:00:00    10
2026-04-06 00:00:00     9
2026-09-07 00:00:00     7
2026-04-07 00:00:00     5
2026-07-06 00:00:00     5
2026-05-07 00:00:00     5
2026-08-06 00:00:00     5
2026-03-08 00:00:00     5
2026-09-05 00:00:00     4
2026-09-06 00:00:00     3
2026-08-05 00:00:00     2
Name: count, dtype: int64

In [79]:
df["QUALITY OF SLEEP"].value_counts()

QUALITY OF SLEEP
8    109
6    105
7     77
9     71
5      7
4      5
Name: count, dtype: int64

In [80]:
df["PHYSICAL ACTIVITY LEVEL"].value_counts()

PHYSICAL ACTIVITY LEVEL
60    70
30    68
45    68
75    67
90    67
40     6
55     6
35     4
50     4
70     3
42     2
32     2
80     2
65     2
85     2
47     1
Name: count, dtype: int64

In [84]:
df["STRESS LEVEL"].value_counts()

STRESS LEVEL
3    71
8    70
4    70
5    67
7    50
6    46
Name: count, dtype: int64

In [86]:
df["BMI CATEGORY"].value_counts()

BMI CATEGORY
Normal           195
Overweight       148
Normal Weight     21
Obese             10
Name: count, dtype: int64

In [88]:
df["HEART RATE"].value_counts()

HEART RATE
68    94
70    76
72    69
65    67
75    36
78     5
85     3
80     3
84     2
83     2
73     2
67     2
74     2
77     2
81     2
76     2
69     2
86     2
82     1
Name: count, dtype: int64

In [90]:
df["DAILY STEPS"].value_counts()

DAILY STEPS
8000     101
6000      68
5000      68
7000      66
10000     36
5500       4
3000       3
3500       3
4000       3
6800       3
4800       2
7300       2
7500       2
4200       2
3300       2
5600       2
5200       2
4100       2
3700       2
6200       1
Name: count, dtype: int64

In [92]:
df["SLEEP DISORDER"].value_counts()

SLEEP DISORDER
No_disease     219
Sleep Apnea     78
Insomnia        77
Name: count, dtype: int64

In [94]:
#11) OCCUPATION sutununda nadir deyerlere baxin, her nadir deyerin sayina da baxin
df["OCCUPATION"].value_counts()

OCCUPATION
Nurse                   73
Doctor                  71
Engineer                63
Lawyer                  47
Teacher                 40
Accountant              37
Salesperson             32
Software Engineer        4
Scientist                4
Sales Representative     2
Manager                  1
Name: count, dtype: int64

In [98]:
#12) Her sutun uzre ortalama cixarin
df.mean(numeric_only=True)

AGE                          42.184492
QUALITY OF SLEEP              7.312834
PHYSICAL ACTIVITY LEVEL      59.171123
STRESS LEVEL                  5.385027
HEART RATE                   70.165775
DAILY STEPS                6816.844920
dtype: float64

In [100]:
#13) DAILY STEPS 10000den az olmayan ve SLEEP DURATION 8den az olmayan setirlere baxin
df["SLEEP DURATION"] = pd.to_numeric(df["SLEEP DURATION"], errors="coerce").astype("Int64") ##inte cevirdi

In [112]:
df[(df["DAILY STEPS"]>1000)& (df["SLEEP DURATION"]<8)]

,GENDER,AGE,OCCUPATION,SLEEP DURATION,QUALITY OF SLEEP,PHYSICAL ACTIVITY LEVEL,STRESS LEVEL,BMI CATEGORY,HEART RATE,DAILY STEPS,SLEEP DISORDER,BP_Systolic,BP_Diastolic
13,Male,29,Doctor,6,6,30,8,Normal,70,8000,No_disease,120,80
14,Male,29,Doctor,6,6,30,8,Normal,70,8000,No_disease,120,80
15,Male,29,Doctor,6,6,30,8,Normal,70,8000,No_disease,120,80
17,Male,29,Doctor,6,6,30,8,Normal,70,8000,Sleep Apnea,120,80
52,Male,32,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
54,Male,32,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
55,Male,32,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
57,Male,32,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
58,Male,32,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
60,Male,32,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
61,Male,32,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
67,Male,33,Doctor,6,6,30,8,Normal,72,5000,Insomnia,125,80
74,Male,33,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
75,Male,33,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
76,Male,33,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
77,Male,33,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
78,Male,33,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
79,Male,33,Doctor,6,6,30,8,Normal,72,5000,No_disease,125,80
268,Female,49,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
280,Female,50,Nurse,6,6,90,8,Overweight,75,10000,No_disease,140,95
282,Female,50,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
283,Female,50,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
284,Female,50,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
285,Female,50,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
286,Female,50,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
287,Female,50,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
288,Female,50,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
290,Female,50,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
293,Female,50,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
295,Female,50,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95
303,Female,51,Nurse,6,6,90,8,Overweight,75,10000,Sleep Apnea,140,95

In [107]:
#14) Yasi 56dan boyuk olanlarin Occupation a baxin
df[df["AGE"]>56]["OCCUPATION"]

343    Nurse
344    Nurse
345    Nurse
346    Nurse
347    Nurse
348    Nurse
349    Nurse
350    Nurse
351    Nurse
352    Nurse
353    Nurse
354    Nurse
355    Nurse
356    Nurse
357    Nurse
358    Nurse
359    Nurse
360    Nurse
361    Nurse
362    Nurse
363    Nurse
364    Nurse
365    Nurse
366    Nurse
367    Nurse
368    Nurse
369    Nurse
370    Nurse
371    Nurse
372    Nurse
373    Nurse
Name: OCCUPATION, dtype: object

In [125]:
#15) Datani yasa gore azalan sira ile duz
df.sort_values(by="AGE", ascending=False)

,PERSON ID,GENDER,AGE,OCCUPATION,SLEEP DURATION,QUALITY OF SLEEP,PHYSICAL ACTIVITY LEVEL,STRESS LEVEL,BMI CATEGORY,BLOOD PRESSURE,HEART RATE,DAILY STEPS,SLEEP DISORDER
373,374,Female,59,Nurse,2026-01-08 00:00:00,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
365,366,Female,59,Nurse,8,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
358,359,Female,59,Nurse,8,9,75,3,Overweight,140/95,68,7000,NaN
359,360,Female,59,Nurse,2026-01-08 00:00:00,9,75,3,Overweight,140/95,68,7000,NaN
360,361,Female,59,Nurse,2026-02-08 00:00:00,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,3,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,NaN
1,2,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,NaN
4,5,Male,28,Sales Representative,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Sleep Apnea
5,6,Male,28,Software Engineer,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Insomnia
0,1,Male,27,Software Engineer,2026-01-06 00:00:00,6,42,6,Overweight,126/83,77,4200,NaN

In [140]:
#16) Indexleri yenile
df.reset_index(inplace=True, drop=True)
df

,GENDER,AGE,OCCUPATION,SLEEP DURATION,QUALITY OF SLEEP,PHYSICAL ACTIVITY LEVEL,STRESS LEVEL,BMI CATEGORY,BLOOD PRESSURE,HEART RATE,DAILY STEPS,SLEEP DISORDER
0,Male,27,Software Engineer,2026-01-06 00:00:00,6,42,6,Overweight,126/83,77,4200,No_disease
1,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,No_disease
2,Male,28,Doctor,2026-02-06 00:00:00,6,60,8,Normal,125/80,75,10000,No_disease
3,Male,28,Sales Representative,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,Male,28,Sales Representative,2026-09-05 00:00:00,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...
369,Female,59,Nurse,2026-01-08 00:00:00,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,Female,59,Nurse,8,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,Female,59,Nurse,2026-01-08 00:00:00,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,Female,59,Nurse,2026-01-08 00:00:00,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,Female,59,Nurse,2026-01-08 00:00:00,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [144]:
'''17) Columns arasi elaqeye baxin
18) Her stress level uzre daily steps in ortalamasina baxin ve sonda daily steps sutununu artan sira ile duzun
19) Sleep disorder ve gender sutunlari arasinda cross seklinde melumatlari cixarin
20) Duplicatlarin sayina baxin'''
df_numeric = df.select_dtypes(include="number")  # numeric olanalrin corelasiyai
df_numeric.corr()

,AGE,QUALITY OF SLEEP,PHYSICAL ACTIVITY LEVEL,STRESS LEVEL,HEART RATE,DAILY STEPS
AGE,1.000000,0.473734,0.178993,-0.422344,-0.225606,0.057973
QUALITY OF SLEEP,0.473734,1.000000,0.192896,-0.898752,-0.659865,0.016791
PHYSICAL ACTIVITY LEVEL,0.178993,0.192896,1.000000,-0.034134,0.136971,0.772723
STRESS LEVEL,-0.422344,-0.898752,-0.034134,1.000000,0.670026,0.186829
HEART RATE,-0.225606,-0.659865,0.136971,0.670026,1.000000,-0.030309
DAILY STEPS,0.057973,0.016791,0.772723,0.186829,-0.030309,1.000000

In [150]:
#18) Her stress level uzre daily steps in ortalamasina baxin ve sonda daily steps sutununu artan sira ile duzun
df.groupby(by="STRESS LEVEL").mean(numeric_only=True)["DAILY STEPS"].sort_values(ascending=False)

STRESS LEVEL
5    7616.417910
8    7605.714286
6    7363.043478
4    6422.857143
3    6132.394366
7    5662.000000
Name: DAILY STEPS, dtype: float64

In [154]:
#19) Sleep disorder ve gender sutunlari arasinda cross seklinde melumatlari cixarin
pd.crosstab(df["SLEEP DISORDER"], df["GENDER"]) ##crosstable edirmisik

GENDER          Female  Male
SLEEP DISORDER
Insomnia            36    41
No_disease          82   137
Sleep Apnea         67    11

In [162]:
#20) Duplicatlarin sayina baxin
df.duplicated().sum() ##umumi dublikat setr sayi 

#df.apply(lambda x: x.duplicated().sum()) ## her column uzre dubliakt deyer sayi

np.int64(242)